from __future__ import annotations

import argparse
import sys
from pathlib import Path

from synthtest.config.loader import load_schema_from_path
from synthtest.gen.core import generate_dataset
from synthtest.profile.infer_basic import infer_basic
from synthtest.validate.validator import validate_output
from synthtest.util.logging import get_logger, log_event

LOGGER = get_logger(__name__)


def main() -> None:
    parser = argparse.ArgumentParser(prog="synthtest", description="SynthTest AI CLI")
    subparsers = parser.add_subparsers(dest="command")

    init_parser = subparsers.add_parser("init", help="Create example config and docs skeleton")

    gen_parser = subparsers.add_parser("generate", help="Generate synthetic data")
    gen_parser.add_argument("--config", required=True, help="Path to schema config")
    gen_parser.add_argument("--out", required=True, help="Output directory")
    gen_parser.add_argument("--format", default="csv", choices=["csv", "json", "sql"], help="Output format")

    val_parser = subparsers.add_parser("validate", help="Validate generated data")
    val_parser.add_argument("--config", required=True, help="Path to schema config")
    val_parser.add_argument("--data", required=True, help="Output directory")
    val_parser.add_argument("--format", default="csv", choices=["csv", "json", "sql"], help="Data format")

    infer_parser = subparsers.add_parser("infer-basic", help="Infer schema from sample CSV")
    infer_parser.add_argument("--input", required=True, help="Input CSV file")
    infer_parser.add_argument("--out", required=True, help="Output schema YAML path")

    args = parser.parse_args()

    if args.command == "init":
        _handle_init()
        return
    if args.command == "generate":
        schema, config_hash = load_schema_from_path(args.config)
        metadata = generate_dataset(schema, config_hash, args.out, args.format)
        log_event(LOGGER, "generation_complete", output=args.out, dataset_id=metadata.dataset_id)
        return
    if args.command == "validate":
        schema, _ = load_schema_from_path(args.config)
        report = validate_output(schema, Path(args.data), args.format)
        report_path = Path(args.data) / "validation_report.json"
        report_path.write_text(report.model_dump_json(indent=2), encoding="utf-8")
        log_event(LOGGER, "validation_complete", output=str(report_path), violations=report.total_violations)
        return
    if args.command == "infer-basic":
        infer_basic(args.input, args.out)
        log_event(LOGGER, "infer_complete", output=args.out)
        return

    parser.print_help()
    sys.exit(1)


def _handle_init() -> None:
    root = Path.cwd()
    examples_dir = root / "examples"
    docs_dir = root / "docs"
    examples_dir.mkdir(parents=True, exist_ok=True)
    docs_dir.mkdir(parents=True, exist_ok=True)

    example_path = examples_dir / "ecommerce.yml"
    if not example_path.exists():
        example_path.write_text(_example_config(), encoding="utf-8")

    for name, content in _docs_skeleton().items():
        path = docs_dir / name
        if not path.exists():
            path.write_text(content, encoding="utf-8")

    log_event(LOGGER, "init_complete", examples=str(example_path), docs=str(docs_dir))


def _example_config() -> str:
    return """dataset:\n  name: ecommerce\n  seed: 12345\n  mode: valid\n  size:\n    customers: 50\n    orders: 200\n  max_attempts: 20\n\ntables:\n  customers:\n    primary_key: customer_id\n    columns:\n      customer_id:\n        type: uuid\n      name:\n        type: name\n      email:\n        type: email\n        unique: true\n      phone:\n        type: phone\n        nullable: true\n      country:\n        type: country\n      postcode:\n        type: postcode_uk\n        nullable: true\n  orders:\n    primary_key: order_id\n    foreign_keys:\n      - column: customer_id\n        ref_table: customers\n        ref_column: customer_id\n    columns:\n      order_id:\n        type: uuid\n      customer_id:\n        type: uuid\n      status:\n        type: enum\n        values: [PAID, FAILED, REFUNDED]\n        weights: [0.7, 0.2, 0.1]\n      total_amount:\n        type: decimal\n        range: [0, 2000]\n        distribution: lognormal\n      created_at:\n        type: datetime\n        range: ["2023-01-01T00:00:00", "2025-01-01T00:00:00"]\n\nrules:\n  - if: "orders.status == 'FAILED'"\n    then:\n      - "orders.total_amount <= 500.0"\n"""


def _docs_skeleton() -> dict[str, str]:
    return {
        "architecture.md": "# Architecture\n\n(autogenerated)\n",
        "config-spec.md": "# Config Spec\n\n(autogenerated)\n",
        "cli.md": "# CLI\n\n(autogenerated)\n",
        "validation-and-metrics.md": "# Validation and Metrics\n\n(autogenerated)\n",
        "security-and-pii.md": "# Security and PII\n\n(autogenerated)\n",
    }
